# Generated by Django 4.1.3 on 2023-01-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterestedMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=250)),
                ("contact", models.CharField(max_length=250)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "member_status",
                    models.CharField(
                        choices=[
                            ("Already a Member", "Already a Member"),
                            ("New Member", "New Member"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
