# Generated by Django 4.1.3 on 2023-01-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auxiliaries"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auxiliaries",
            old_name="code",
            new_name="designation",
        ),
        migrations.AddField(
            model_name="auxiliaries",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
