# Generated by Django 4.1.3 on 2023-01-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_code_auxiliaries_designation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ministries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(default="group.png", upload_to="ministries"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="auxiliaries",
            name="image",
            field=models.ImageField(default="group.png", upload_to="auxiliaries"),
        ),
        migrations.AlterField(
            model_name="family",
            name="image",
            field=models.ImageField(default="group.png", upload_to="family"),
        ),
    ]
