# Generated by Django 4.1.3 on 2023-01-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_ministries_alter_auxiliaries_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuxiliaryMeetings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days", models.CharField(blank=True, max_length=50, null=True)),
                ("time", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "auxiliary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="auxiliary",
                        to="core.auxiliaries",
                    ),
                ),
            ],
        ),
    ]
