# Generated by Django 4.1.3 on 2023-01-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auxiliarymeetings"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpcomingEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="auxiliarymeetings",
            name="auxiliary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="auxiliary_meeting",
                to="core.auxiliaries",
            ),
        ),
    ]
