# Generated by Django 4.1.3 on 2023-01-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_upcomingevents_alter_auxiliarymeetings_auxiliary"),
    ]

    operations = [
        migrations.AddField(
            model_name="upcomingevents",
            name="completed",
            field=models.BooleanField(default="False"),
        ),
    ]
