# Generated by Django 4.1.3 on 2023-01-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_upcomingevents_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upcomingevents",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
