# Generated by Django 4.1.3 on 2023-01-23 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_upcomingevents_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuxiliaryExecutives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default.jpg",
                        null=True,
                        upload_to="profile_pics",
                    ),
                ),
                ("phone_no", models.CharField(blank=True, max_length=20, null=True)),
                ("facebook", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "auxiliary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="auxiliary_executives",
                        to="core.auxiliaries",
                    ),
                ),
            ],
        ),
    ]
