# Generated by Django 4.1.3 on 2023-01-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auxiliaryexecutives"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("text", models.TextField()),
            ],
        ),
    ]
