# Generated by Django 4.1.3 on 2023-01-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_faq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="text",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="title",
            new_name="question",
        ),
    ]
