# Generated by Django 4.1.3 on 2023-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_rename_image_auxiliaries_deacon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="family",
            name="image",
        ),
        migrations.AddField(
            model_name="family",
            name="deacon",
            field=models.ImageField(default="group.png", upload_to="auxiliaries"),
        ),
        migrations.AddField(
            model_name="family",
            name="group_img",
            field=models.ImageField(default="group.png", upload_to="auxiliaries"),
        ),
    ]
