# Generated by Django 4.1.3 on 2023-01-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_family_image_family_deacon_family_group_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="family",
            name="code",
        ),
    ]
