# Generated by Django 4.1.3 on 2023-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_family_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="mission",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="speech",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="vision",
            field=models.TextField(blank=True, null=True),
        ),
    ]
