# Generated by Django 4.1.3 on 2023-01-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_family_mission_family_speech_family_vision"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250)),
                ("answer", models.TextField()),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="family_faqs",
                        to="core.auxiliaries",
                    ),
                ),
            ],
        ),
    ]
