# Generated by Django 4.1.3 on 2023-01-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_familyfaq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auxiliaries",
            old_name="description",
            new_name="mission",
        ),
        migrations.AddField(
            model_name="auxiliaries",
            name="speech",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auxiliaries",
            name="vision",
            field=models.TextField(blank=True, null=True),
        ),
    ]
