# Generated by Django 4.1.3 on 2023-01-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_rename_description_auxiliaries_mission_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ministries",
            old_name="designation",
            new_name="goal",
        ),
        migrations.AddField(
            model_name="ministries",
            name="speech",
            field=models.TextField(blank=True, null=True),
        ),
    ]
