# Generated by Django 4.1.3 on 2023-01-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_rename_designation_ministries_goal_ministries_speech"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
