# Generated by Django 4.1.3 on 2023-01-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="days",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="services",
            name="times",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
