# Generated by Django 4.1.3 on 2023-01-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_sermon"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="contact",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
