# Generated by Django 4.1.3 on 2023-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_auxiliaries_deacon_alter_auxiliaries_group_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="auxiliaryexecutives",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
