# Generated by Django 4.1.3 on 2023-02-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_auxiliaryexecutives_whatsapp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auxiliaries",
            old_name="vision",
            new_name="about_us",
        ),
    ]
