# Generated by Django 4.1.3 on 2023-02-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_rename_vision_auxiliaries_about_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Services", "Service"),
                            ("Youth", "Youth"),
                            ("Projects", "Projects"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default.jpg",
                        null=True,
                        upload_to="profile_pics",
                    ),
                ),
                ("detail", models.CharField(max_length=255)),
            ],
        ),
    ]
