# Generated by Django 4.1.3 on 2023-04-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_mission_family_location_remove_family_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sermon', 'Sermon'), ('Salvation', 'Salvation'), ('Marriages', 'Marriages'), ('Others', 'Others')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='book_cover.jpg', null=True, upload_to='books_pics')),
                ('detail', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookscategory')),
            ],
        ),
    ]
