# Generated by Django 4.1.3 on 2023-04-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_detail_books_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auxiliaries',
            old_name='deacon',
            new_name='president_picture',
        ),
    ]
