# Generated by Django 4.1.3 on 2023-04-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_deacon_auxiliaries_president_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministries',
            name='image',
        ),
        migrations.AddField(
            model_name='ministries',
            name='deacon_picture',
            field=models.ImageField(default='deafult.png', upload_to='ministries'),
        ),
        migrations.AddField(
            model_name='ministries',
            name='group_img',
            field=models.ImageField(blank=True, default='group.png', null=True, upload_to='ministries'),
        ),
    ]
