# Generated by Django 4.1.3 on 2023-04-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_ministries_image_ministries_deacon_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministries',
            name='deacon_picture',
            field=models.ImageField(default='default.png', upload_to='ministries'),
        ),
    ]
