# Generated by Django 4.1.3 on 2023-04-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_ministries_deacon_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministries',
            name='image',
            field=models.ImageField(default='default.png', upload_to='ministries'),
        ),
    ]
