# Generated by Django 4.1.3 on 2023-04-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_ministries_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='deacon',
            new_name='deacon_img',
        ),
        migrations.AddField(
            model_name='ministries',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
