# Generated by Django 4.1.3 on 2023-04-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
