# Generated by Django 4.1.3 on 2023-01-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0006_alter_profile_auxiliary_alter_profile_family_and_more"),
        ("accounts", "0002_cashflows"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CashFlows",
            new_name="CashFlow",
        ),
    ]
