# Generated by Django 4.1.3 on 2023-01-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_cashflow_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="returned_to",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
