# Generated by Django 4.1.3 on 2023-01-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_cashflow_returned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashflow",
            name="returned_amount",
        ),
    ]
