# Generated by Django 4.1.3 on 2023-01-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0006_alter_profile_auxiliary_alter_profile_family_and_more"),
        ("accounts", "0006_remove_cashflow_returned_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashFlowHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "image",
                    models.ImageField(default="product.png", upload_to="category_pics"),
                ),
                ("receipt_no", models.CharField(blank=True, max_length=50, null=True)),
                ("item_description", models.TextField(blank=True, null=True)),
                ("amount", models.IntegerField(blank=True, default="0", null=True)),
                ("returned_to", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.category",
                    ),
                ),
                (
                    "received_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="authy.profile",
                    ),
                ),
            ],
        ),
    ]
