# Generated by Django 4.1.3 on 2023-01-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_cashhistory_issue_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cash",
            name="issue_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
