# Generated by Django 4.1.3 on 2023-01-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0008_delete_cash"),
        ("accounts", "0012_alter_cashflow_received_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="received_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sale_to",
                to="authy.profile",
            ),
        ),
    ]
