# Generated by Django 4.1.3 on 2023-01-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_cashflow_received_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="cash",
            name="receipt_no",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
