# Generated by Django 4.1.3 on 2023-04-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_cash_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='category',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('Mobile Money', 'Mobile Money')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashhistory',
            name='category',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('Mobile Money', 'Mobile Money')], max_length=50, null=True),
        ),
    ]
