# Generated by Django 4.1.3 on 2023-01-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="club",
            new_name="family",
        ),
    ]
