# Generated by Django 4.1.3 on 2023-01-13 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_code_auxiliaries_designation_and_more"),
        ("authy", "0002_rename_club_profile_family"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_type",
        ),
        migrations.AddField(
            model_name="profile",
            name="auxiliaries",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.auxiliaries",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="marriage_status",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Widowed", "Widowed"),
                ],
                default="User",
                max_length=20,
            ),
        ),
    ]
