# Generated by Django 4.1.3 on 2023-01-16 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0003_remove_profile_user_type_profile_auxiliaries_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="first_name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="phone",
            new_name="phone_no",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="last_name",
            new_name="place_of_residence",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="marriage_status",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="next_of_kin",
        ),
        migrations.AddField(
            model_name="profile",
            name="baptism",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="Yes", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("O-", "O-"),
                    ("O+", "O+"),
                    ("A-", "A-"),
                    ("A+", "A+"),
                    ("AB-", "AB-"),
                    ("AB+", "AB+"),
                    ("B-", "B"),
                    ("B+", "B+"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="date_joined",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No Formal Education", "No Formal Education"),
                    ("Junior High", "Junior High"),
                    ("Senior High", "Senior High"),
                    ("HND", "HND"),
                    ("Diploma", "Diploma"),
                    ("Degree", "Degree"),
                    ("Masters", "Masters"),
                    ("PHD", "PHD"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="father_alive",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="Yes", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="father_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="hometown",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Widowed", "Widowed"),
                ],
                default="Single",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="mother_alive",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="Yes", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="mother_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="no_of_children",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="organisation_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="spouse",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Unemployed", "Unemployed"),
                    ("Employed", "Employed"),
                    ("Student", "Student"),
                ],
                default="Student",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="next_of_kin_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
