# Generated by Django 4.1.3 on 2023-01-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_ministries_alter_auxiliaries_image_and_more"),
        ("authy", "0004_rename_first_name_profile_full_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="auxiliaries",
        ),
        migrations.AddField(
            model_name="profile",
            name="auxiliary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="auxiliaries",
                to="core.auxiliaries",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ministry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ministries",
                to="core.ministries",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="baptism",
            field=models.CharField(
                choices=[
                    ("Water", "Water"),
                    ("Holy Ghost", "Holy Ghost"),
                    ("Both", "Both"),
                    ("Not Yet", "Not Yet"),
                ],
                default="Not Yet",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="family",
                to="core.family",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="no_of_children",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
