# Generated by Django 4.1.3 on 2023-01-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auxiliarymeetings"),
        ("authy", "0005_remove_profile_auxiliaries_profile_auxiliary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="auxiliary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.auxiliaries",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.family",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ministry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.ministries",
            ),
        ),
    ]
