# Generated by Django 4.1.3 on 2023-01-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0007_cash"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cash",
        ),
    ]
