# Generated by Django 4.1.3 on 2023-01-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_family_contact"),
        ("authy", "0008_delete_cash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="family",
                to="core.family",
            ),
        ),
    ]
