# Generated by Django 4.1.3 on 2023-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0010_alter_profile_blood_group_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_deacon',
            field=models.BooleanField(default=False),
        ),
    ]
