# Generated by Django 4.1.3 on 2023-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0011_profile_is_deacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_council_member',
            field=models.BooleanField(default=False),
        ),
    ]
