# Generated by Django 4.1.3 on 2023-04-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0012_profile_is_council_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('B-', 'B'), ('B+', 'B+')], max_length=50, null=True)),
                ('place_of_residence', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('No Formal Education', 'No Formal Education'), ('Junior High', 'Junior High'), ('Senior High', 'Senior High'), ('HND', 'HND'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('PHD', 'PHD')], max_length=50, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('hometown', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=20)),
                ('next_of_kin_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('ssnit', models.CharField(blank=True, max_length=50, null=True)),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
