# Generated by Django 4.1.3 on 2023-04-27 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0015_position_appointed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='appointed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
