# Generated by Django 4.1.3 on 2023-04-28 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0016_alter_position_appointed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_hours', models.CharField(max_length=20)),
                ('office_days', models.CharField(max_length=20)),
                ('at_office', models.BooleanField(default=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authy.position')),
            ],
        ),
    ]
